In [1]:
import numpy as np

In [2]:
m = 11

n = 11

image = np.random.randint(0, 255, size=(m, n, 3))

image

array([[[213, 187, 254],
        [137,  51,  80],
        [221, 141, 222],
        [241, 161,  68],
        [142,  50,  59],
        [ 52, 135, 204],
        [ 39,  66, 149],
        [209,  56,  47],
        [ 59,  11,  92],
        [ 43, 126,  36],
        [227, 194, 210]],

       [[ 43,  89,  51],
        [241, 176, 205],
        [102, 247,  23],
        [158,  90,  46],
        [106,  80, 226],
        [ 86, 118,  88],
        [ 28,  12,  92],
        [241, 102, 212],
        [ 46, 206,  51],
        [126,  45, 132],
        [ 28,  92, 142]],

       [[179, 167,   3],
        [ 83,  60,  52],
        [ 71, 232,  84],
        [ 26,  36,  44],
        [199, 108,   7],
        [ 31, 111, 242],
        [126, 212, 209],
        [206,   3, 226],
        [194,   7,  36],
        [235,  93, 137],
        [143, 161,  73]],

       [[ 98, 106,  56],
        [242,  27,  92],
        [ 34, 146,  72],
        [ 46,  87, 148],
        [ 48,  13, 118],
        [ 66, 200, 105],
        [218, 111, 

In [3]:
image.shape

(11, 11, 3)

In [4]:
R = image[:, :, 0]

R

array([[213, 137, 221, 241, 142,  52,  39, 209,  59,  43, 227],
       [ 43, 241, 102, 158, 106,  86,  28, 241,  46, 126,  28],
       [179,  83,  71,  26, 199,  31, 126, 206, 194, 235, 143],
       [ 98, 242,  34,  46,  48,  66, 218, 177, 162, 198, 185],
       [245, 228, 137, 234, 145, 227,   0,  74, 111,  37,  67],
       [ 40,  96, 162, 171, 246,  37, 149, 177, 159,  31, 218],
       [ 76, 193, 217, 185, 124, 203,  31, 230,  52, 199, 215],
       [114, 189, 239,  82, 151,  74, 226,  39,  46, 227,  70],
       [ 12, 252, 238,  30, 160, 162,  34, 241, 124, 211, 114],
       [120,  15, 212, 202, 210, 245,  13, 128,  22, 185, 102],
       [172, 169, 247,  14, 231, 137, 243,  13, 151, 222, 173]])

In [5]:
G = image[:, :, 1]

G

array([[187,  51, 141, 161,  50, 135,  66,  56,  11, 126, 194],
       [ 89, 176, 247,  90,  80, 118,  12, 102, 206,  45,  92],
       [167,  60, 232,  36, 108, 111, 212,   3,   7,  93, 161],
       [106,  27, 146,  87,  13, 200, 111,  52,  13,  46, 106],
       [163, 230,  13, 142, 188, 145, 238, 147, 120,  94,  14],
       [ 80, 184,  37,  65, 113,  16,  87, 174,  48,  41, 196],
       [ 12, 170, 108,  29,  73, 188, 242,  40,  63,  15,  35],
       [ 44, 117,  94,  58,  59,   0, 116, 111, 239, 195, 123],
       [ 55,  53,  77,  70, 166, 160,  30, 222,  54, 224, 164],
       [153, 125, 195,  83,  37,   3,  25, 139,  72, 206, 225],
       [  8, 159, 181,  11, 157, 173, 163, 131,   1, 203,  23]])

In [6]:
B = image[:, :, 2]

B

array([[254,  80, 222,  68,  59, 204, 149,  47,  92,  36, 210],
       [ 51, 205,  23,  46, 226,  88,  92, 212,  51, 132, 142],
       [  3,  52,  84,  44,   7, 242, 209, 226,  36, 137,  73],
       [ 56,  92,  72, 148, 118, 105, 119,  25, 161, 112, 201],
       [ 76, 174,   0, 155,  46,  56, 147, 107,  80,  67, 163],
       [171,  45,  28, 231, 193,  86,  41, 199, 210, 175,  28],
       [181, 157, 141,  65, 206,  79, 138, 156, 106, 177, 115],
       [252,  88, 244, 254,  40, 204, 236, 192,  15, 213,   2],
       [209, 155, 140, 116,  77, 134, 229,   1, 173, 145,  34],
       [212, 118, 203, 193, 162, 239,  69,   6,  78, 217,  88],
       [ 67,   5, 244, 212, 157, 157, 226, 139,  85, 215, 235]])

In [7]:
bayer_array = np.zeros((m, n), dtype = int)

bayer_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
for i in range(m):
    for j in range(n):
        if i%2 == 0 and j%2 == 0:
            bayer_array[i, j] = R[i, j]
        elif i%2 != 0 and j%2 !=0:
            bayer_array[i, j] = B[i, j]
        else:
            bayer_array[i, j] = G[i, j]

In [9]:
bayer_array

array([[213,  51, 221, 161, 142, 135,  39,  56,  59, 126, 227],
       [ 89, 205, 247,  46,  80,  88,  12, 212, 206, 132,  92],
       [179,  60,  71,  36, 199, 111, 126,   3, 194,  93, 143],
       [106,  92, 146, 148,  13, 105, 111,  25,  13, 112, 106],
       [245, 230, 137, 142, 145, 145,   0, 147, 111,  94,  67],
       [ 80,  45,  37, 231, 113,  86,  87, 199,  48, 175, 196],
       [ 76, 170, 217,  29, 124, 188,  31,  40,  52,  15, 215],
       [ 44,  88,  94, 254,  59, 204, 116, 192, 239, 213, 123],
       [ 12,  53, 238,  70, 160, 160,  34, 222, 124, 224, 114],
       [153, 118, 195, 193,  37, 239,  25,   6,  72, 217, 225],
       [172, 159, 247,  11, 231, 173, 243, 131, 151, 203, 173]])

In [10]:
I2 = array = np.full((m, n, 3), -1)

I2

array([[[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1],
        [-1, -1, -1]],

       [[-1, -1, -1],
  

In [11]:
R2 = I2[:, :, 0].copy()

G2 = I2[:, :, 1].copy()

B2 = I2[:, :, 2].copy()

In [12]:
for i in range(m):
    for j in range(n):
        if i%2 == 0 and j%2 == 0:
            R2[i, j] = bayer_array[i, j]
        elif i%2 != 0 and j%2 !=0:
            B2[i, j] = bayer_array[i, j]
        else:
            G2[i, j] = bayer_array[i, j]
            

In [13]:
R2

array([[213,  -1, 221,  -1, 142,  -1,  39,  -1,  59,  -1, 227],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [179,  -1,  71,  -1, 199,  -1, 126,  -1, 194,  -1, 143],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [245,  -1, 137,  -1, 145,  -1,   0,  -1, 111,  -1,  67],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ 76,  -1, 217,  -1, 124,  -1,  31,  -1,  52,  -1, 215],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ 12,  -1, 238,  -1, 160,  -1,  34,  -1, 124,  -1, 114],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [172,  -1, 247,  -1, 231,  -1, 243,  -1, 151,  -1, 173]])

In [14]:
for i in range(m):
    for j in range(n):
        if i % 2 == 0 and j% 2 ==0:
            if i+1 < m and j+1 < n:
                R2[i+1, 1+j] = R2[i, j]
            if j+1 < n:
                R2[i, j+1] = R2[i, j]
            if i+1 < m:
                R2[i+1, j] = R2[i, j]
        

In [15]:
R2

array([[213, 213, 221, 221, 142, 142,  39,  39,  59,  59, 227],
       [213, 213, 221, 221, 142, 142,  39,  39,  59,  59, 227],
       [179, 179,  71,  71, 199, 199, 126, 126, 194, 194, 143],
       [179, 179,  71,  71, 199, 199, 126, 126, 194, 194, 143],
       [245, 245, 137, 137, 145, 145,   0,   0, 111, 111,  67],
       [245, 245, 137, 137, 145, 145,   0,   0, 111, 111,  67],
       [ 76,  76, 217, 217, 124, 124,  31,  31,  52,  52, 215],
       [ 76,  76, 217, 217, 124, 124,  31,  31,  52,  52, 215],
       [ 12,  12, 238, 238, 160, 160,  34,  34, 124, 124, 114],
       [ 12,  12, 238, 238, 160, 160,  34,  34, 124, 124, 114],
       [172, 172, 247, 247, 231, 231, 243, 243, 151, 151, 173]])

In [16]:
B2

array([[ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 205,  -1,  46,  -1,  88,  -1, 212,  -1, 132,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  92,  -1, 148,  -1, 105,  -1,  25,  -1, 112,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  45,  -1, 231,  -1,  86,  -1, 199,  -1, 175,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  88,  -1, 254,  -1, 204,  -1, 192,  -1, 213,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1, 118,  -1, 193,  -1, 239,  -1,   6,  -1, 217,  -1],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1]])

In [17]:
for i in range(m):
    for j in range(n):
        if i % 2 != 0 and j % 2 != 0:
            B2[i-1, j-1] = B2[i, j]
            B2[i, j-1] = B2[i, j]
            B2[i-1, j] = B2[i, j]    
        
    
for i in range(m):
    for j in range(n):         
        if j == n-1:
            B2[i, j] = B2[i, j-1]  
        if i == m-1:
            B2[i, j] = B2[i-1, j]

In [18]:
B2

array([[205, 205,  46,  46,  88,  88, 212, 212, 132, 132, 132],
       [205, 205,  46,  46,  88,  88, 212, 212, 132, 132, 132],
       [ 92,  92, 148, 148, 105, 105,  25,  25, 112, 112, 112],
       [ 92,  92, 148, 148, 105, 105,  25,  25, 112, 112, 112],
       [ 45,  45, 231, 231,  86,  86, 199, 199, 175, 175, 175],
       [ 45,  45, 231, 231,  86,  86, 199, 199, 175, 175, 175],
       [ 88,  88, 254, 254, 204, 204, 192, 192, 213, 213, 213],
       [ 88,  88, 254, 254, 204, 204, 192, 192, 213, 213, 213],
       [118, 118, 193, 193, 239, 239,   6,   6, 217, 217, 217],
       [118, 118, 193, 193, 239, 239,   6,   6, 217, 217, 217],
       [118, 118, 193, 193, 239, 239,   6,   6, 217, 217, 217]])

In [19]:
G2

array([[ -1,  51,  -1, 161,  -1, 135,  -1,  56,  -1, 126,  -1],
       [ 89,  -1, 247,  -1,  80,  -1,  12,  -1, 206,  -1,  92],
       [ -1,  60,  -1,  36,  -1, 111,  -1,   3,  -1,  93,  -1],
       [106,  -1, 146,  -1,  13,  -1, 111,  -1,  13,  -1, 106],
       [ -1, 230,  -1, 142,  -1, 145,  -1, 147,  -1,  94,  -1],
       [ 80,  -1,  37,  -1, 113,  -1,  87,  -1,  48,  -1, 196],
       [ -1, 170,  -1,  29,  -1, 188,  -1,  40,  -1,  15,  -1],
       [ 44,  -1,  94,  -1,  59,  -1, 116,  -1, 239,  -1, 123],
       [ -1,  53,  -1,  70,  -1, 160,  -1, 222,  -1, 224,  -1],
       [153,  -1, 195,  -1,  37,  -1,  25,  -1,  72,  -1, 225],
       [ -1, 159,  -1,  11,  -1, 173,  -1, 131,  -1, 203,  -1]])

In [20]:
for i in range(m):
    for j in range(1, n, 2):
        if i % 2 == 0:
            G2[i, j - 1] = G2[i, j]
            if j == n-2:
                G2[i, j+1] = G2[i, j]

In [21]:
G2

array([[ 51,  51, 161, 161, 135, 135,  56,  56, 126, 126, 126],
       [ 89,  -1, 247,  -1,  80,  -1,  12,  -1, 206,  -1,  92],
       [ 60,  60,  36,  36, 111, 111,   3,   3,  93,  93,  93],
       [106,  -1, 146,  -1,  13,  -1, 111,  -1,  13,  -1, 106],
       [230, 230, 142, 142, 145, 145, 147, 147,  94,  94,  94],
       [ 80,  -1,  37,  -1, 113,  -1,  87,  -1,  48,  -1, 196],
       [170, 170,  29,  29, 188, 188,  40,  40,  15,  15,  15],
       [ 44,  -1,  94,  -1,  59,  -1, 116,  -1, 239,  -1, 123],
       [ 53,  53,  70,  70, 160, 160, 222, 222, 224, 224, 224],
       [153,  -1, 195,  -1,  37,  -1,  25,  -1,  72,  -1, 225],
       [159, 159,  11,  11, 173, 173, 131, 131, 203, 203, 203]])

In [22]:
for i in range(m):
    for j in range(0, n, 2):
        if i % 2 != 0 and j+1 < n:
            G2[i, j + 1] = G2[i, j]

In [23]:
G2

array([[ 51,  51, 161, 161, 135, 135,  56,  56, 126, 126, 126],
       [ 89,  89, 247, 247,  80,  80,  12,  12, 206, 206,  92],
       [ 60,  60,  36,  36, 111, 111,   3,   3,  93,  93,  93],
       [106, 106, 146, 146,  13,  13, 111, 111,  13,  13, 106],
       [230, 230, 142, 142, 145, 145, 147, 147,  94,  94,  94],
       [ 80,  80,  37,  37, 113, 113,  87,  87,  48,  48, 196],
       [170, 170,  29,  29, 188, 188,  40,  40,  15,  15,  15],
       [ 44,  44,  94,  94,  59,  59, 116, 116, 239, 239, 123],
       [ 53,  53,  70,  70, 160, 160, 222, 222, 224, 224, 224],
       [153, 153, 195, 195,  37,  37,  25,  25,  72,  72, 225],
       [159, 159,  11,  11, 173, 173, 131, 131, 203, 203, 203]])

In [24]:
I2[:, :, 0] = R2

I2[:, :, 1] = B2

I2[:, :, 2] = G2

I2

array([[[213, 205,  51],
        [213, 205,  51],
        [221,  46, 161],
        [221,  46, 161],
        [142,  88, 135],
        [142,  88, 135],
        [ 39, 212,  56],
        [ 39, 212,  56],
        [ 59, 132, 126],
        [ 59, 132, 126],
        [227, 132, 126]],

       [[213, 205,  89],
        [213, 205,  89],
        [221,  46, 247],
        [221,  46, 247],
        [142,  88,  80],
        [142,  88,  80],
        [ 39, 212,  12],
        [ 39, 212,  12],
        [ 59, 132, 206],
        [ 59, 132, 206],
        [227, 132,  92]],

       [[179,  92,  60],
        [179,  92,  60],
        [ 71, 148,  36],
        [ 71, 148,  36],
        [199, 105, 111],
        [199, 105, 111],
        [126,  25,   3],
        [126,  25,   3],
        [194, 112,  93],
        [194, 112,  93],
        [143, 112,  93]],

       [[179,  92, 106],
        [179,  92, 106],
        [ 71, 148, 146],
        [ 71, 148, 146],
        [199, 105,  13],
        [199, 105,  13],
        [126,  25, 

In [25]:
image

array([[[213, 187, 254],
        [137,  51,  80],
        [221, 141, 222],
        [241, 161,  68],
        [142,  50,  59],
        [ 52, 135, 204],
        [ 39,  66, 149],
        [209,  56,  47],
        [ 59,  11,  92],
        [ 43, 126,  36],
        [227, 194, 210]],

       [[ 43,  89,  51],
        [241, 176, 205],
        [102, 247,  23],
        [158,  90,  46],
        [106,  80, 226],
        [ 86, 118,  88],
        [ 28,  12,  92],
        [241, 102, 212],
        [ 46, 206,  51],
        [126,  45, 132],
        [ 28,  92, 142]],

       [[179, 167,   3],
        [ 83,  60,  52],
        [ 71, 232,  84],
        [ 26,  36,  44],
        [199, 108,   7],
        [ 31, 111, 242],
        [126, 212, 209],
        [206,   3, 226],
        [194,   7,  36],
        [235,  93, 137],
        [143, 161,  73]],

       [[ 98, 106,  56],
        [242,  27,  92],
        [ 34, 146,  72],
        [ 46,  87, 148],
        [ 48,  13, 118],
        [ 66, 200, 105],
        [218, 111, 

In [26]:
mse = np.mean((image - I2) ** 2)

print(f"MSE: {mse}")

MSE: 10789.41873278237


In [27]:
max_pixel_value = 255.0

psnr = 10 * np.log10((max_pixel_value ** 2) / mse)

print(f"PSNR: {psnr} dB")

PSNR: 7.800823126581221 dB
