Esercizio n°1

In [1]:
import numpy as np

import random

In [2]:
m = int(input("Insert number of rows:"))

n = int(input("Insert number of columns:"))

image = np.random.randint(0, 255, size=(m, n, 3))

In [3]:
# Define a function that swaps even-numbered columns with odd-numbered columns and viceversa
def swap_col(img):
    swap_img = img.copy()
    for i in range(m):
        for j in range(0, n-1, 2):
            swap_img[i,j] = img[i, j+1]
            swap_img[i,j+1] = img[i, j]
        
    return swap_img

In [4]:
swap_col(image)

array([[[ 30, 229, 112],
        [190,  44, 198],
        [248,  64, 161],
        [103,   6,  36],
        [253, 247, 140],
        [ 68,  43, 141],
        [227,  55, 253],
        [ 73,  67, 198],
        [ 40, 116, 184],
        [134, 180, 175]],

       [[108, 238,  95],
        [ 97, 246, 142],
        [  6, 188, 237],
        [ 44, 177,   1],
        [ 51, 206, 204],
        [178,   8, 111],
        [  8,  50, 151],
        [131,  93,  94],
        [ 46, 113,   1],
        [166,   3,  73]],

       [[ 68, 148,  85],
        [196,  93,  75],
        [218,  42,  38],
        [ 73, 170, 199],
        [203, 158, 220],
        [185, 228,  49],
        [ 88, 242, 142],
        [157, 164, 242],
        [184, 237, 114],
        [117, 249,  23]],

       [[132, 133,   0],
        [136, 182,  17],
        [ 49, 195,  20],
        [ 17,  29, 167],
        [136, 239,  80],
        [123,  21,  54],
        [ 19, 207, 224],
        [ 11, 168, 195],
        [ 88, 150,  28],
        [ 35, 178, 

In [5]:
image

array([[[190,  44, 198],
        [ 30, 229, 112],
        [103,   6,  36],
        [248,  64, 161],
        [ 68,  43, 141],
        [253, 247, 140],
        [ 73,  67, 198],
        [227,  55, 253],
        [134, 180, 175],
        [ 40, 116, 184]],

       [[ 97, 246, 142],
        [108, 238,  95],
        [ 44, 177,   1],
        [  6, 188, 237],
        [178,   8, 111],
        [ 51, 206, 204],
        [131,  93,  94],
        [  8,  50, 151],
        [166,   3,  73],
        [ 46, 113,   1]],

       [[196,  93,  75],
        [ 68, 148,  85],
        [ 73, 170, 199],
        [218,  42,  38],
        [185, 228,  49],
        [203, 158, 220],
        [157, 164, 242],
        [ 88, 242, 142],
        [117, 249,  23],
        [184, 237, 114]],

       [[136, 182,  17],
        [132, 133,   0],
        [ 17,  29, 167],
        [ 49, 195,  20],
        [123,  21,  54],
        [136, 239,  80],
        [ 11, 168, 195],
        [ 19, 207, 224],
        [ 35, 178,  33],
        [ 88, 150, 

In [6]:
#Define a function that exchanges even rows with odd rows and vice versa

def swap_row(img):
    swap_img = img.copy()
    for i in range(0, m-1, 2):
        for j in range(n):
            swap_img[i,j] = img[i+1, j]
            swap_img[i+1,j] = img[i, j]
        
    return swap_img

In [7]:
swap_row(image)

array([[[ 97, 246, 142],
        [108, 238,  95],
        [ 44, 177,   1],
        [  6, 188, 237],
        [178,   8, 111],
        [ 51, 206, 204],
        [131,  93,  94],
        [  8,  50, 151],
        [166,   3,  73],
        [ 46, 113,   1]],

       [[190,  44, 198],
        [ 30, 229, 112],
        [103,   6,  36],
        [248,  64, 161],
        [ 68,  43, 141],
        [253, 247, 140],
        [ 73,  67, 198],
        [227,  55, 253],
        [134, 180, 175],
        [ 40, 116, 184]],

       [[136, 182,  17],
        [132, 133,   0],
        [ 17,  29, 167],
        [ 49, 195,  20],
        [123,  21,  54],
        [136, 239,  80],
        [ 11, 168, 195],
        [ 19, 207, 224],
        [ 35, 178,  33],
        [ 88, 150,  28]],

       [[196,  93,  75],
        [ 68, 148,  85],
        [ 73, 170, 199],
        [218,  42,  38],
        [185, 228,  49],
        [203, 158, 220],
        [157, 164, 242],
        [ 88, 242, 142],
        [117, 249,  23],
        [184, 237, 

In [8]:
image

array([[[190,  44, 198],
        [ 30, 229, 112],
        [103,   6,  36],
        [248,  64, 161],
        [ 68,  43, 141],
        [253, 247, 140],
        [ 73,  67, 198],
        [227,  55, 253],
        [134, 180, 175],
        [ 40, 116, 184]],

       [[ 97, 246, 142],
        [108, 238,  95],
        [ 44, 177,   1],
        [  6, 188, 237],
        [178,   8, 111],
        [ 51, 206, 204],
        [131,  93,  94],
        [  8,  50, 151],
        [166,   3,  73],
        [ 46, 113,   1]],

       [[196,  93,  75],
        [ 68, 148,  85],
        [ 73, 170, 199],
        [218,  42,  38],
        [185, 228,  49],
        [203, 158, 220],
        [157, 164, 242],
        [ 88, 242, 142],
        [117, 249,  23],
        [184, 237, 114]],

       [[136, 182,  17],
        [132, 133,   0],
        [ 17,  29, 167],
        [ 49, 195,  20],
        [123,  21,  54],
        [136, 239,  80],
        [ 11, 168, 195],
        [ 19, 207, 224],
        [ 35, 178,  33],
        [ 88, 150, 

In [9]:
X = 229

def set_to_zero(img):
    X = int(input("Select a random number X, if one of the pixel's channels has a value equal to X, all the channels are set to 0")) 
    for x in range(m):
        for y in range(n):
            for z in range(3):
                if img[x, y, z] == X:
                    img[x, y] = 0
    return image

In [10]:
set_to_zero(image)

array([[[190,  44, 198],
        [ 30, 229, 112],
        [103,   6,  36],
        [248,  64, 161],
        [ 68,  43, 141],
        [253, 247, 140],
        [ 73,  67, 198],
        [227,  55, 253],
        [134, 180, 175],
        [ 40, 116, 184]],

       [[ 97, 246, 142],
        [108, 238,  95],
        [ 44, 177,   1],
        [  6, 188, 237],
        [178,   8, 111],
        [ 51, 206, 204],
        [131,  93,  94],
        [  8,  50, 151],
        [166,   3,  73],
        [ 46, 113,   1]],

       [[196,  93,  75],
        [ 68, 148,  85],
        [ 73, 170, 199],
        [218,  42,  38],
        [185, 228,  49],
        [203, 158, 220],
        [157, 164, 242],
        [ 88, 242, 142],
        [117, 249,  23],
        [184, 237, 114]],

       [[136, 182,  17],
        [132, 133,   0],
        [ 17,  29, 167],
        [ 49, 195,  20],
        [123,  21,  54],
        [136, 239,  80],
        [ 11, 168, 195],
        [ 19, 207, 224],
        [ 35, 178,  33],
        [ 88, 150, 

Esercizio n°2

In [11]:
n = int(input("Select n"))

matrix = np.random.randint(0, 256, size=(n, n,3))


In [12]:
matrix

array([[[194,  69, 159],
        [ 13, 154, 151],
        [184,  27,  28],
        [ 23, 102,  82],
        [ 33,  35,  56],
        [ 98,  43,  19],
        [181,  79, 220],
        [175,  90, 190],
        [209, 169, 110],
        [ 84,  10, 120]],

       [[ 28,   0,  10],
        [ 11,  81, 185],
        [195, 117, 143],
        [146,  34, 186],
        [192, 145,  40],
        [ 34, 242,  83],
        [249, 175, 214],
        [155, 247,  27],
        [ 48,  48, 195],
        [100, 232,  35]],

       [[ 71, 166,   7],
        [243,  64, 149],
        [223,  39, 156],
        [116,  30, 123],
        [ 38,  40, 138],
        [140, 165, 188],
        [ 78, 199,  20],
        [245,  10, 249],
        [ 86,  52, 139],
        [ 58,  98,   0]],

       [[199, 170, 134],
        [ 25,  60,   5],
        [121,  74,  61],
        [119, 215, 240],
        [ 94, 195, 178],
        [210, 176,  58],
        [251,  44,  62],
        [100, 144,  66],
        [160, 152, 222],
        [191,  92, 

In [13]:
mat = matrix.copy()
            

In [14]:
for i in range(n):
    for j in range(n):
        for z in range(3):
            if i == j:
                mat[i , j, z] = matrix[i , -j-1, z]
            #mat[i , -j-1] = 0
            

In [15]:
mat

array([[[ 84,  10, 120],
        [ 13, 154, 151],
        [184,  27,  28],
        [ 23, 102,  82],
        [ 33,  35,  56],
        [ 98,  43,  19],
        [181,  79, 220],
        [175,  90, 190],
        [209, 169, 110],
        [ 84,  10, 120]],

       [[ 28,   0,  10],
        [ 48,  48, 195],
        [195, 117, 143],
        [146,  34, 186],
        [192, 145,  40],
        [ 34, 242,  83],
        [249, 175, 214],
        [155, 247,  27],
        [ 48,  48, 195],
        [100, 232,  35]],

       [[ 71, 166,   7],
        [243,  64, 149],
        [245,  10, 249],
        [116,  30, 123],
        [ 38,  40, 138],
        [140, 165, 188],
        [ 78, 199,  20],
        [245,  10, 249],
        [ 86,  52, 139],
        [ 58,  98,   0]],

       [[199, 170, 134],
        [ 25,  60,   5],
        [121,  74,  61],
        [251,  44,  62],
        [ 94, 195, 178],
        [210, 176,  58],
        [251,  44,  62],
        [100, 144,  66],
        [160, 152, 222],
        [191,  92, 

In [16]:
S = 100

for i in range(n):
    for j in range(n):
        for z in range(3):
            if mat[i, j, z] < S:
                mat[i, j] = 0
            else:
                mat[i, j] = 255

In [17]:
mat

array([[[  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255]],

       [[  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 

Esercizio n°3

In [18]:
#n = int(input("Choose the number of rows"))

n = 5
m = 5
ex_3 = np.random.randint(0, 25,(n, m, 3))

x = 2
y = 2

w = 2
h = 2

ex_3


array([[[15,  1,  3],
        [23, 20, 13],
        [ 0, 23,  7],
        [17, 23, 23],
        [ 3,  6, 14]],

       [[20,  0,  1],
        [ 7, 15,  2],
        [ 6, 22, 13],
        [10, 22, 20],
        [19, 11, 23]],

       [[23, 22,  2],
        [ 4,  1,  1],
        [12, 18,  6],
        [ 3, 13,  0],
        [23, 16,  6]],

       [[10,  4,  6],
        [ 7, 18, 22],
        [21,  7, 21],
        [22, 15, 12],
        [ 5, 15,  6]],

       [[11, 21, 15],
        [ 5,  2, 10],
        [14,  7, 18],
        [ 5, 17, 14],
        [ 0,  8, 15]]])

In [19]:
M1 = ex_3[x:x+w, y:y+h, 0] 
M2 = ex_3[x:x+w, y:y+h, 1] 
M3 = ex_3[x:x+w, y:y+h, 2] 

In [20]:
M1

array([[12,  3],
       [21, 22]])

In [21]:
M2

array([[18, 13],
       [ 7, 15]])

In [22]:
copym1 = M1.copy
copym2 = M2.copy
copym3 = M3.copy

In [23]:
ex_3[x:x+w, y:y+h, 0] = 0
ex_3[x:x+w, y:y+h, 1] = 0
ex_3[x:x+w, y:y+h, 2] = 0

In [24]:
ex_3

array([[[15,  1,  3],
        [23, 20, 13],
        [ 0, 23,  7],
        [17, 23, 23],
        [ 3,  6, 14]],

       [[20,  0,  1],
        [ 7, 15,  2],
        [ 6, 22, 13],
        [10, 22, 20],
        [19, 11, 23]],

       [[23, 22,  2],
        [ 4,  1,  1],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [23, 16,  6]],

       [[10,  4,  6],
        [ 7, 18, 22],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 5, 15,  6]],

       [[11, 21, 15],
        [ 5,  2, 10],
        [14,  7, 18],
        [ 5, 17, 14],
        [ 0,  8, 15]]])

Esercizio n°4 

In [25]:
#n = int(input("Select number of rows"))

n = 10

m = 10

ex4 = np.random.randint(0, 256, (n, m), dtype = "uint8")

In [26]:
ex4

array([[  2, 221,  42, 231,  95,  88, 191, 237, 250,   7],
       [223, 193,  72, 211,  56, 118, 222, 138, 146, 187],
       [ 37,   1, 124, 117, 191, 132,  40, 148,  53,  47],
       [193, 158,  26,  85, 201, 108,  99, 228, 229,  97],
       [ 45, 230, 117, 203, 168, 110, 254, 217, 178, 143],
       [ 74,  62,  71, 205, 136,  18,  84,  21, 179, 232],
       [ 32, 166,  16, 233, 241, 238, 197,  91, 135, 187],
       [210,   9,  51, 117, 172, 146,  27,  18, 102, 134],
       [233,  63,  10, 177, 169,   5, 230, 232,  27, 124],
       [166, 242, 127,   7,  39, 141, 166, 181, 242, 253]], dtype=uint8)

In [27]:
for i in range(2, n-1, 2):
    for j in range(2, m-1, 2):
        for z in range(3):
            if z ==1:
                ex4[i, j] = ex4[i-1, j]/4 + ex4[i+1, j]/4 + ex4[i, j-1]/4 + ex4[i, j+1]/4
                
for i in range(1, n-1, 2):
    for j in range(1, m-1, 2):
        for z in range(3):
            if z == 0 or z ==2:
                ex4[i, j] = ex4[i-1, j]/4 + ex4[i+1, j]/4 + ex4[i, j-1]/4 + ex4[i, j+1]/4
                         

In [28]:
ex4

array([[  2, 221,  42, 231,  95,  88, 191, 237, 250,   7],
       [223, 129,  72, 119,  56, 124, 222, 188, 146, 187],
       [ 37,   1,  54, 117, 126, 132, 150, 148, 142,  47],
       [193, 112,  26, 136, 201, 135,  99, 173, 229,  97],
       [ 45, 230, 132, 203, 162, 110, 127, 217, 192, 143],
       [ 74, 135,  71, 160, 136, 142,  84, 142, 179, 232],
       [ 32, 166, 130, 233, 194, 238, 110,  91, 139, 187],
       [210, 122,  51, 158, 172, 110,  27, 113, 102, 134],
       [233,  63, 104, 177,  98,   5, 107, 232, 175, 124],
       [166, 242, 127,   7,  39, 141, 166, 181, 242, 253]], dtype=uint8)

Esercizio n°5

Esercizio n°6

In [29]:
matrix = np.random.randint(0, 256, (10, 10, 3), dtype="uint8")

In [30]:
matrix

array([[[252,  17, 183],
        [132, 110,  54],
        [ 79, 189, 232],
        [142, 149, 130],
        [171,  93,  84],
        [239,  14, 105],
        [124,  94, 209],
        [171, 251, 166],
        [ 52, 175,  38],
        [139, 242,  64]],

       [[ 86, 195,  34],
        [121,  79, 193],
        [229, 107, 117],
        [209, 112, 230],
        [ 35, 205,  27],
        [132, 230, 186],
        [ 39, 171, 134],
        [108,  32, 128],
        [201, 226, 244],
        [ 18, 154, 121]],

       [[ 80, 113, 188],
        [ 33,  64,   4],
        [186,   0, 149],
        [234,  23, 190],
        [ 14, 179, 174],
        [201,  31, 225],
        [183, 127,  33],
        [222, 200,  39],
        [164,  25,  23],
        [158, 151,  41]],

       [[254, 239,  98],
        [227, 144,  58],
        [249, 223, 138],
        [ 19,  57, 237],
        [ 65, 208, 204],
        [230,  86, 122],
        [111, 246, 174],
        [127,  35, 201],
        [ 18,  82,  73],
        [235,  11, 

In [31]:
negative_matrix = 255 - matrix

In [32]:
negative_matrix

array([[[  3, 238,  72],
        [123, 145, 201],
        [176,  66,  23],
        [113, 106, 125],
        [ 84, 162, 171],
        [ 16, 241, 150],
        [131, 161,  46],
        [ 84,   4,  89],
        [203,  80, 217],
        [116,  13, 191]],

       [[169,  60, 221],
        [134, 176,  62],
        [ 26, 148, 138],
        [ 46, 143,  25],
        [220,  50, 228],
        [123,  25,  69],
        [216,  84, 121],
        [147, 223, 127],
        [ 54,  29,  11],
        [237, 101, 134]],

       [[175, 142,  67],
        [222, 191, 251],
        [ 69, 255, 106],
        [ 21, 232,  65],
        [241,  76,  81],
        [ 54, 224,  30],
        [ 72, 128, 222],
        [ 33,  55, 216],
        [ 91, 230, 232],
        [ 97, 104, 214]],

       [[  1,  16, 157],
        [ 28, 111, 197],
        [  6,  32, 117],
        [236, 198,  18],
        [190,  47,  51],
        [ 25, 169, 133],
        [144,   9,  81],
        [128, 220,  54],
        [237, 173, 182],
        [ 20, 244, 

Esercizio n°7

In [33]:
m = 5

n = 5

matrix = np.random.randint(0, 256, (m, n), dtype = "uint8")

res = np.zeros((matrix.shape[0],matrix.shape[1]), dtype ="uint8" )

In [34]:
matrix

array([[ 50,  60, 227,   1, 228],
       [203,   3,  87,  29, 225],
       [ 68,  17, 101,  18,  51],
       [193,  47, 149, 112, 182],
       [107, 223, 133, 134, 102]], dtype=uint8)

In [35]:
res

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

### This is wrong !!

In [36]:
for i in range(0, m, 2):
    for j in range(0, n, 2):
        patch = matrix[i:i+2, j:j+2]
        minimum = np.min(patch)
        res[i, j] = minimum
        

In [37]:
res

array([[  3,   0,   1,   0, 225],
       [  0,   0,   0,   0,   0],
       [ 17,   0,  18,   0,  51],
       [  0,   0,   0,   0,   0],
       [107,   0, 133,   0, 102]], dtype=uint8)

### This is correct!!

In [38]:
matrix = np.random.randint(0, 256, (10, 7), dtype= "uint8")
m, n = matrix.shape

res = np.empty((m // 2 + m % 2, n // 2 + n % 2), dtype="uint8")

for i in range(0, m, 2):
    for j in range(0, n, 2):
        patch = matrix[i:min(i+2, m), j:min(j+2, n)]
        minimum = np.min(patch)
        res[i // 2, j // 2] = minimum

print(res)

[[115  62  16 164]
 [ 17 117 137  64]
 [ 44  45  63   0]
 [ 65  93  67 165]
 [ 31  12  13   1]]


In [39]:
matrix = np.random.randint(0, 256, (7, 6), dtype= "uint8")
m, n = matrix.shape

res = np.empty((m // 2 + m % 2, n // 2 + n % 2), dtype="uint8")

for i in range(0, m, 2):
    for j in range(0, n, 2):
        patch = matrix[i:min(i+2, m), j:min(j+2, n)]
        maximum = np.max(patch)
        res[i // 2, j // 2] = maximum

print(res)

[[142 217 141]
 [236 250 128]
 [250 238 254]
 [ 26 215 223]]


In [40]:
matrix = np.random.randint(0, 256, (7, 6), dtype= "uint8")
m, n = matrix.shape

res = np.empty((m // 2 + m % 2, n // 2 + n % 2), dtype="uint8")

for i in range(0, m, 2):
    for j in range(0, n, 2):
        patch = matrix[i:min(i+2, m), j:min(j+2, n)]
        average = np.average(patch)
        res[i // 2, j // 2] = average

print(res)

[[130 125 101]
 [173 158 161]
 [ 73 133 117]
 [148 168 108]]


Esercizio n°8 - Da completare

In [41]:
matrix = np.random.randint(0, 256,(10, 10, 3), dtype="uint8")

In [42]:
def zoom_in(img):
    h = img.shape[0]
    w = img.shape[1]
    zoom_pic = np.zeros((k*h, w), dtype = int)
    for i in range(h//2):
        for j in range(w//2):
            zoom_pic[2*i, 2*j] = img[i, j]
            zoom_pic[2*i + 1, 2*j + 1] = img[i, j]
            zoom_pic[2*i + 1, 2*j] = img[i, j]
            zoom_pic[2*i, 2*j + 1] = img[i, j]
    

Esercizio n°9

Esercizio n°10

In [43]:
matrix = np.random.randint(0, 256, (10, 10, 3), dtype = "uint8")

In [44]:
p1 = np.zeros((matrix.shape[0], matrix.shape[1], matrix.shape[2]), dtype = "uint8")

In [45]:
R = matrix[:, :, 0]

G = matrix[:, :, 1]

B = matrix[:, :, 2]

In [46]:
R2 = np.zeros((10, 10, 3),dtype= "uint8")

In [47]:
for i in range(10):
    for j in range(10):
        for z in range(3):
            R2[i, j, 0] = R[i, j]
            R2[i, j, 1] = 0
            R2[i, j, 2] = 0

In [48]:
R2

array([[[176,   0,   0],
        [161,   0,   0],
        [211,   0,   0],
        [207,   0,   0],
        [ 32,   0,   0],
        [ 99,   0,   0],
        [240,   0,   0],
        [208,   0,   0],
        [149,   0,   0],
        [126,   0,   0]],

       [[  0,   0,   0],
        [172,   0,   0],
        [ 53,   0,   0],
        [ 48,   0,   0],
        [189,   0,   0],
        [244,   0,   0],
        [147,   0,   0],
        [238,   0,   0],
        [ 22,   0,   0],
        [ 24,   0,   0]],

       [[ 20,   0,   0],
        [ 20,   0,   0],
        [ 12,   0,   0],
        [ 75,   0,   0],
        [205,   0,   0],
        [197,   0,   0],
        [210,   0,   0],
        [ 69,   0,   0],
        [ 51,   0,   0],
        [245,   0,   0]],

       [[ 88,   0,   0],
        [232,   0,   0],
        [198,   0,   0],
        [ 48,   0,   0],
        [ 27,   0,   0],
        [223,   0,   0],
        [155,   0,   0],
        [ 42,   0,   0],
        [ 19,   0,   0],
        [ 89,   0, 

In [49]:
R

array([[176, 161, 211, 207,  32,  99, 240, 208, 149, 126],
       [  0, 172,  53,  48, 189, 244, 147, 238,  22,  24],
       [ 20,  20,  12,  75, 205, 197, 210,  69,  51, 245],
       [ 88, 232, 198,  48,  27, 223, 155,  42,  19,  89],
       [156, 159,  44, 243,  18, 213, 193,  22,  15, 213],
       [ 20, 237, 115,  36, 165,  84, 215,  77, 179, 193],
       [ 15,  78, 216,  88, 184, 196, 133, 206,  73, 208],
       [251,  64, 239,  66,  26, 157, 211, 235, 146,  15],
       [234,  24,  90, 174,   4,  61,  87, 252,  17, 201],
       [ 91,   2, 165, 230, 160, 198,  86, 200, 130,  78]], dtype=uint8)

In [50]:
G2 = np.zeros((10, 10, 3), dtype = "uint8")

for i in range(10):
    for j in range(10):
        for z in range(3):
            G2[i, j, 1] = G[i, j]
            G2[i, j, 0] = 0
            G2[i, j, 2] = 0


In [51]:
G2

array([[[  0, 131,   0],
        [  0,  41,   0],
        [  0,  91,   0],
        [  0, 151,   0],
        [  0, 210,   0],
        [  0, 117,   0],
        [  0,  45,   0],
        [  0, 166,   0],
        [  0,  33,   0],
        [  0,  72,   0]],

       [[  0,  54,   0],
        [  0,  67,   0],
        [  0, 159,   0],
        [  0, 212,   0],
        [  0, 240,   0],
        [  0,  79,   0],
        [  0, 100,   0],
        [  0, 195,   0],
        [  0, 101,   0],
        [  0,  46,   0]],

       [[  0,  20,   0],
        [  0, 228,   0],
        [  0, 242,   0],
        [  0,  89,   0],
        [  0, 236,   0],
        [  0, 136,   0],
        [  0,  20,   0],
        [  0, 207,   0],
        [  0,   3,   0],
        [  0, 182,   0]],

       [[  0, 242,   0],
        [  0,  26,   0],
        [  0, 226,   0],
        [  0, 255,   0],
        [  0, 213,   0],
        [  0, 167,   0],
        [  0, 222,   0],
        [  0, 184,   0],
        [  0,  90,   0],
        [  0, 186, 

In [52]:
B2 = np.zeros((10, 10, 3), dtype = "uint8")

for i in range(10):
    for j in range(10):
        for z in range(3):
            B2[i, j, 2] = B[i, j]
            B2[i, j, 0] = 0
            B2[i, j, 1] = 0

In [53]:
B2

array([[[  0,   0,  89],
        [  0,   0, 151],
        [  0,   0, 200],
        [  0,   0, 231],
        [  0,   0,  65],
        [  0,   0, 114],
        [  0,   0, 119],
        [  0,   0, 108],
        [  0,   0, 134],
        [  0,   0, 126]],

       [[  0,   0,  49],
        [  0,   0, 250],
        [  0,   0, 113],
        [  0,   0,  70],
        [  0,   0, 195],
        [  0,   0,  70],
        [  0,   0,  42],
        [  0,   0, 188],
        [  0,   0, 201],
        [  0,   0, 174]],

       [[  0,   0, 187],
        [  0,   0, 184],
        [  0,   0,  97],
        [  0,   0,  89],
        [  0,   0, 199],
        [  0,   0, 183],
        [  0,   0,  60],
        [  0,   0,  21],
        [  0,   0,  41],
        [  0,   0, 209]],

       [[  0,   0, 173],
        [  0,   0, 182],
        [  0,   0,  73],
        [  0,   0, 230],
        [  0,   0, 157],
        [  0,   0,  60],
        [  0,   0, 184],
        [  0,   0, 127],
        [  0,   0, 101],
        [  0,   0, 

In [54]:
for i in range(10):
    for j in range(0, 10, 2):
        for z in range(3):
            if i % 2 == 0:
                p1[i, j, z] = G2[i, j, z]
            if i % 2 != 0:
                p1[i, j, z] = B2[i, j, z]

In [55]:
p1

array([[[  0, 131,   0],
        [  0,   0,   0],
        [  0,  91,   0],
        [  0,   0,   0],
        [  0, 210,   0],
        [  0,   0,   0],
        [  0,  45,   0],
        [  0,   0,   0],
        [  0,  33,   0],
        [  0,   0,   0]],

       [[  0,   0,  49],
        [  0,   0,   0],
        [  0,   0, 113],
        [  0,   0,   0],
        [  0,   0, 195],
        [  0,   0,   0],
        [  0,   0,  42],
        [  0,   0,   0],
        [  0,   0, 201],
        [  0,   0,   0]],

       [[  0,  20,   0],
        [  0,   0,   0],
        [  0, 242,   0],
        [  0,   0,   0],
        [  0, 236,   0],
        [  0,   0,   0],
        [  0,  20,   0],
        [  0,   0,   0],
        [  0,   3,   0],
        [  0,   0,   0]],

       [[  0,   0, 173],
        [  0,   0,   0],
        [  0,   0,  73],
        [  0,   0,   0],
        [  0,   0, 157],
        [  0,   0,   0],
        [  0,   0, 184],
        [  0,   0,   0],
        [  0,   0, 101],
        [  0,   0, 

In [56]:
for i in range(10):
    for j in range(1, 10, 2):
        for z in range(3):
            if i % 2 == 0:
                p1[i, j, z] = R2[i, j, z]
            if i % 2 != 0:
                p1[i, j, z] = G2[i, j, z]

In [57]:
p1

array([[[  0, 131,   0],
        [161,   0,   0],
        [  0,  91,   0],
        [207,   0,   0],
        [  0, 210,   0],
        [ 99,   0,   0],
        [  0,  45,   0],
        [208,   0,   0],
        [  0,  33,   0],
        [126,   0,   0]],

       [[  0,   0,  49],
        [  0,  67,   0],
        [  0,   0, 113],
        [  0, 212,   0],
        [  0,   0, 195],
        [  0,  79,   0],
        [  0,   0,  42],
        [  0, 195,   0],
        [  0,   0, 201],
        [  0,  46,   0]],

       [[  0,  20,   0],
        [ 20,   0,   0],
        [  0, 242,   0],
        [ 75,   0,   0],
        [  0, 236,   0],
        [197,   0,   0],
        [  0,  20,   0],
        [ 69,   0,   0],
        [  0,   3,   0],
        [245,   0,   0]],

       [[  0,   0, 173],
        [  0,  26,   0],
        [  0,   0,  73],
        [  0, 255,   0],
        [  0,   0, 157],
        [  0, 167,   0],
        [  0,   0, 184],
        [  0, 184,   0],
        [  0,   0, 101],
        [  0, 186, 

In [58]:
p2 = np.zeros((10, 10, 3), dtype = "uint8")

In [59]:
for i in range(10):
    for j in range(0, 10, 2):
        p2[i, j] = B2[i, j]

In [60]:
p2

array([[[  0,   0,  89],
        [  0,   0,   0],
        [  0,   0, 200],
        [  0,   0,   0],
        [  0,   0,  65],
        [  0,   0,   0],
        [  0,   0, 119],
        [  0,   0,   0],
        [  0,   0, 134],
        [  0,   0,   0]],

       [[  0,   0,  49],
        [  0,   0,   0],
        [  0,   0, 113],
        [  0,   0,   0],
        [  0,   0, 195],
        [  0,   0,   0],
        [  0,   0,  42],
        [  0,   0,   0],
        [  0,   0, 201],
        [  0,   0,   0]],

       [[  0,   0, 187],
        [  0,   0,   0],
        [  0,   0,  97],
        [  0,   0,   0],
        [  0,   0, 199],
        [  0,   0,   0],
        [  0,   0,  60],
        [  0,   0,   0],
        [  0,   0,  41],
        [  0,   0,   0]],

       [[  0,   0, 173],
        [  0,   0,   0],
        [  0,   0,  73],
        [  0,   0,   0],
        [  0,   0, 157],
        [  0,   0,   0],
        [  0,   0, 184],
        [  0,   0,   0],
        [  0,   0, 101],
        [  0,   0, 

In [61]:
for i in range(10):
    for j in range(1, 10, 4):
        if i % 2 == 0:
            p2[i, j] = R2[i, j]
        if i % 2 !=0:
            p2[i, j] = B2[i, j]
            

In [62]:
for i in range(10):
    for j in range(3, 10, 4):
        if i % 2 == 0:
            p2[i, j] = B2[i, j]
        if i % 2 !=0:
            p2[i, j] = R2[i, j]

In [63]:
R2

array([[[176,   0,   0],
        [161,   0,   0],
        [211,   0,   0],
        [207,   0,   0],
        [ 32,   0,   0],
        [ 99,   0,   0],
        [240,   0,   0],
        [208,   0,   0],
        [149,   0,   0],
        [126,   0,   0]],

       [[  0,   0,   0],
        [172,   0,   0],
        [ 53,   0,   0],
        [ 48,   0,   0],
        [189,   0,   0],
        [244,   0,   0],
        [147,   0,   0],
        [238,   0,   0],
        [ 22,   0,   0],
        [ 24,   0,   0]],

       [[ 20,   0,   0],
        [ 20,   0,   0],
        [ 12,   0,   0],
        [ 75,   0,   0],
        [205,   0,   0],
        [197,   0,   0],
        [210,   0,   0],
        [ 69,   0,   0],
        [ 51,   0,   0],
        [245,   0,   0]],

       [[ 88,   0,   0],
        [232,   0,   0],
        [198,   0,   0],
        [ 48,   0,   0],
        [ 27,   0,   0],
        [223,   0,   0],
        [155,   0,   0],
        [ 42,   0,   0],
        [ 19,   0,   0],
        [ 89,   0, 

In [64]:
p2

array([[[  0,   0,  89],
        [161,   0,   0],
        [  0,   0, 200],
        [  0,   0, 231],
        [  0,   0,  65],
        [ 99,   0,   0],
        [  0,   0, 119],
        [  0,   0, 108],
        [  0,   0, 134],
        [126,   0,   0]],

       [[  0,   0,  49],
        [  0,   0, 250],
        [  0,   0, 113],
        [ 48,   0,   0],
        [  0,   0, 195],
        [  0,   0,  70],
        [  0,   0,  42],
        [238,   0,   0],
        [  0,   0, 201],
        [  0,   0, 174]],

       [[  0,   0, 187],
        [ 20,   0,   0],
        [  0,   0,  97],
        [  0,   0,  89],
        [  0,   0, 199],
        [197,   0,   0],
        [  0,   0,  60],
        [  0,   0,  21],
        [  0,   0,  41],
        [245,   0,   0]],

       [[  0,   0, 173],
        [  0,   0, 182],
        [  0,   0,  73],
        [ 48,   0,   0],
        [  0,   0, 157],
        [  0,   0,  60],
        [  0,   0, 184],
        [ 42,   0,   0],
        [  0,   0, 101],
        [  0,   0, 

In [65]:
p3 = np.zeros((10, 10, 3), dtype = "uint8")

In [66]:
for i in range(0, 10, 4):
    for j in range(10):
        if j % 2 == 0:
            p3[i, j] = B2[i, j]
        if j % 2 != 0:
            p3[i, j] = R2[i, j]

In [67]:
for i in range(1, 10, 4):
    for j in range(10):
        if j % 2 == 0:
            p3[i, j] = B2[i, j]
        if j % 2 != 0:
            p3[i, j] = B2[i, j]

In [68]:
for i in range(2, 10, 4):
    for j in range(10):
        if j % 2 == 0:
            p3[i, j] = R2[i, j]
        if j % 2 != 0:
            p3[i, j] = B2[i, j]

In [69]:
for i in range(3, 10, 4):
    for j in range(10):
        if j % 2 == 0:
            p3[i, j] = B2[i, j]
        if j % 2 != 0:
            p3[i, j] = G2[i, j]

In [70]:
p3

array([[[  0,   0,  89],
        [161,   0,   0],
        [  0,   0, 200],
        [207,   0,   0],
        [  0,   0,  65],
        [ 99,   0,   0],
        [  0,   0, 119],
        [208,   0,   0],
        [  0,   0, 134],
        [126,   0,   0]],

       [[  0,   0,  49],
        [  0,   0, 250],
        [  0,   0, 113],
        [  0,   0,  70],
        [  0,   0, 195],
        [  0,   0,  70],
        [  0,   0,  42],
        [  0,   0, 188],
        [  0,   0, 201],
        [  0,   0, 174]],

       [[ 20,   0,   0],
        [  0,   0, 184],
        [ 12,   0,   0],
        [  0,   0,  89],
        [205,   0,   0],
        [  0,   0, 183],
        [210,   0,   0],
        [  0,   0,  21],
        [ 51,   0,   0],
        [  0,   0, 209]],

       [[  0,   0, 173],
        [  0,  26,   0],
        [  0,   0,  73],
        [  0, 255,   0],
        [  0,   0, 157],
        [  0, 167,   0],
        [  0,   0, 184],
        [  0, 184,   0],
        [  0,   0, 101],
        [  0, 186, 

Esercizio n°11

In [71]:
from sympy import symbols, Eq, solve

a0, a1, a2, a3 = symbols('a0 a1 a2 a3')

eq1 = Eq(a0 + 4*a1 + 4*a2 + 16*a3, 5)
eq2 = Eq(a0 + 4*a1 + 6*a2 + 24*a3, 1)
eq3 = Eq(a0 + 6*a1 + 4*a2 + 24*a3, 12)
eq4 = Eq(a0 + 6*a1 + 6*a2 + 36*a3, 4)

solution = solve((eq1, eq2, eq3, eq4), (a0, a1, a2, a3))
solution


{a0: -17, a1: 15/2, a2: 2, a3: -1}

In [72]:
v_5_5 = (-17 + 5*7.5 + 2*5 -1*25)

v_5_5

5.5

Esercizio n°12

In [73]:
b0, b1, b2, b3 = symbols('b0 b1 b2 b3')

eq1 = Eq(b0 + 3*b1 + b2 + 3*b3, 156)
eq2 = Eq(b0 + 3*b1 + 3*b2 + 9*b3, 21)
eq3 = Eq(b0 + 5*b1 + b2 + 5*b3, 1)
eq4 = Eq(b0 + 5*b1 + 3*b2 + 15*b3, 4)

solve((eq1, eq2, eq3, eq4), (b0, b1, b2, b3))

{b0: 1119/2, b1: -112, b2: -171, b3: 69/2}

In [74]:
v_2_4 = (1119/2 + 2*-112 + 4*-171 + 8*69/2)

v_2_4

-72.5