In [2]:
import numpy as np

In [3]:
x = np.zeros(3)

x

array([0., 0., 0.])

In [4]:
for i in range(len(x)):
    print(x[i])

0.0
0.0
0.0


In [5]:
y = np.zeros((2,3))

print(y)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
for elem in y:
    print(elem)

[0. 0. 0.]
[0. 0. 0.]


In [7]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [8]:
type(x)

numpy.ndarray

In [9]:
a = [2,5,3,7,8,5,3,8,2]
b = [7,8,5,3,2,5,1,9,1]
c = []
for i in range(len(a)):
    c.append(a[i]*b[i])
    
print(c)

[14, 40, 15, 21, 16, 25, 3, 72, 2]


In [10]:
a1D = np.array([1,2,3,4])

a1D

array([1, 2, 3, 4])

In [11]:
a2D = np.array([[1,2],[3,4]])

a2D

array([[1, 2],
       [3, 4]])

In [12]:
type(a2D)

numpy.ndarray

In [13]:
a3D = np.array([[[1,2,3], [1, 2, 3]], [[4,5,6], [4, 5, 6]], [[7, 8, 9], [7, 8, 9]]])

a3D

array([[[1, 2, 3],
        [1, 2, 3]],

       [[4, 5, 6],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 8, 9]]])

In [14]:
a3D.shape

(3, 2, 3)

In [15]:
# Int 8 means we are using 8 bits of storage space and can hold 256 values (2^8)
a = np.array([127, 128, 129], dtype=np.int8)
a

OverflowError: Python integer 128 out of bounds for int8

In [22]:
b = np.array([127, -128, 120], dtype=np.int8)
b

array([ 127, -128,  120], dtype=int8)

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2,10, dtype = float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

For identity matrix ( 2 dimensional matrix with 1 on main diagonal) we can use the followiing:

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

Diagonal matrix 

In [29]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [25]:
np.diag([1, 2, 3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [32]:
a = np.array([[1, 2], [3, 4]])

a

array([[1, 2],
       [3, 4]])

In [33]:
np.diag(a)

array([1, 4])

In [34]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [27]:
from numpy.random import default_rng

In [28]:
default_rng(42).random((2, 3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [44]:
default_rng(42).random((2, 3, 2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [46]:
grid = np.indices((4, 4))

print(grid)


[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]


In [29]:
a = np.array([1,2,3,4,5,6])

a

array([1, 2, 3, 4, 5, 6])

In [49]:
b = a[:2]

b

array([1, 2])

In [51]:
b += 1

b

array([3, 4])

In [52]:
print('a :', a, '; b =', b)

a : [3 4 3 4 5 6] ; b = [3 4]


Doing this, we basically overwrite the a np.array

In [54]:
a = np.array([1, 2, 3, 4, 5, 6])

a

array([1, 2, 3, 4, 5, 6])

In [55]:
b = a[:2].copy()

b 

array([1, 2])

In [57]:
b += 1

b

array([3, 4])

In [58]:
print('a :', a, '; b :', b)

a : [1 2 3 4 5 6] ; b : [3 4]


Indexing on ndarrays

In [14]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
print(x[3])

3


In [17]:
x.shape

(10,)

In [20]:
y = np.array([[1, 2, 3],[4, 5, 6]])

y

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
y.shape

(2, 3)

In [24]:
x.shape = (2, 5)

x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
print(x[1,4])

9


In [30]:
print(x[1, -1])

9


In [32]:
x[0]

array([0, 1, 2, 3, 4])

In [34]:
print(x[0,3])

3


In [35]:
print(x[0][3])

3


In [36]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [37]:
x[-2:10]

array([8, 9])

In [38]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [41]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x #2 blocks, 3 rows per block, 1 column per row

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [44]:
x[1]

array([[4],
       [5],
       [6]])

In [45]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [46]:
x.ndim

3

In [48]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[0: step = 2])

[1 3 5 7]


In [49]:
arr.dtype


dtype('int64')

In [50]:
arr = np.array([1, 2, 3, 4], dtype = 'f')

In [51]:
arr

array([1., 2., 3., 4.], dtype=float32)

In [53]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a[0]

a += 1

print(b)

[2 3 4]


In [54]:
a.shape

(2, 3)

NameError: name 'random' is not defined

In [16]:
import random 

In [18]:
np.random.randint(100)

49

In [19]:
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]


In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]
