In [1]:
import numpy as np

In [2]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [5]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr = np.random.rand(3,3)

arr

array([[0.60270755, 0.10775466, 0.34391458],
       [0.73756194, 0.27720954, 0.47338258],
       [0.81137288, 0.9355711 , 0.765187  ]])

In [9]:
arr = np.array([1, 2, 3, 4, 5])

somma = np.sum(arr)

somma

np.int64(15)

In [10]:
arr = np.array([2, 4, 6, 8, 10])

media = np.mean(arr)

media

np.float64(6.0)

In [11]:
arr = np.arange(1, 17).reshape(4,4)

arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

diagonale = np.diag(arr)

diagonale

array([1, 5, 9])

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr_2d = arr.reshape(3, 2)

arr_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr_concat = np.vstack((arr1, arr2))

arr_concat

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

even = np.where(arr % 2 == 0)[0]

even

array([1, 3, 5, 7])

In [21]:
arr = np.eye(5)

arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr = np.array([1, 2, 3, 4, 5])

arr_norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

arr_norm

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
v1 = np.array([1, 2, 3])

v2 = np.array([4, 5, 6])

dot_product = np.dot(v1, v2)

dot_product

np.int64(32)

In [26]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([4, 5, 6, 7, 8])

comuni = np.intersect1d(arr1, arr2)

comuni

array([4, 5])

In [27]:
arr = np.random.rand(5, 3)

corr_matrix = np.corrcoef(arr.T)

corr_matrix

array([[1.        , 0.20186173, 0.38527207],
       [0.20186173, 1.        , 0.05337716],
       [0.38527207, 0.05337716, 1.        ]])

In [28]:
def funzione_personalizzata(x):
    return x**2 + 2*x + 1

arr = np.array([1, 2, 3, 4, 5])
risultato = np.vectorize(funzione_personalizzata)(arr)
print(risultato)

[ 4  9 16 25 36]


In [31]:
arr_3d = np.random.randint(0, 101, size=(3, 10, 10))
print(arr_3d)

[[[ 98  37   5  94  65  80  66   4  37  80]
  [ 52  79  92  87  71  37  98  50  78  52]
  [  3   4  57   0  98 100  66  61  66  22]
  [ 85   1  48  73  38  75  58  20  61  87]
  [ 56  17  97  55  95  43  61  61  87   0]
  [ 42  38  26  51  29  48  24  73  51  69]
  [  1  69  63  16  20  21  45  13  47 100]
  [ 85  95  18  19  63   1  99  53 100  23]
  [ 64  31  93  89  99  13  15  38  25  34]
  [ 37  16  11  73  73  51   9  56  47  64]]

 [[ 92  32  53  61  16  23  25  63  96  92]
  [  6  10  97  36  74  72  22  59  23  92]
  [ 75  95  55  74  58  14  80   6  49  90]
  [ 30   7  87  49  26  48  54  22  29  58]
  [ 60  27  87  60  23  91  60  99  76  28]
  [ 63  58  54  97 100  29  72  37  38   0]
  [ 57  85  93  26  49   3  21  94  65  45]
  [ 92  64   4  60  51  65  25  13  52  50]
  [ 47  74  96  37  79  25   6  27  15   4]
  [ 60  83  57   0  33   2  98  77  29  98]]

 [[ 53  44  39  45  37  58  94  68  79  79]
  [ 32  89  84  66  21  25  86  84  44  74]
  [ 72  36  30  99  17  14  

In [32]:
arr = np.array([1.2, 3.7, 5.3, 2.9, 8.1])
numero = 3.0
indice = np.abs(arr - numero).argmin()
print(f"L'indice del valore più vicino a {numero} è: {indice}")

L'indice del valore più vicino a 3.0 è: 3


In [33]:
vector = np.array([1, 2, 3, 4, 5])
print("1D Array:", vector)

1D Array: [1 2 3 4 5]


In [34]:
print("First element:", vector[0])

First element: 1


In [35]:
vector[1] = 10
print("Modified Array:", vector)

Modified Array: [ 1 10  3  4  5]


In [36]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", matrix)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [37]:
print("First Row:", matrix[0])

First Row: [1 2 3]


In [38]:
print("Second Column:", matrix[:, 1])

Second Column: [2 5]


In [40]:
for element in vector:
    print(element * 2) # Print each element multiplied by 2

2
20
6
8
10


In [41]:
for row in matrix:
    for element in row:
        print(element ** 2) # Print each element squared

1
4
9
16
25
36


In [42]:
for element in vector:
    if element > 3:
        print("Greater than 3:", element)

Greater than 3: 10
Greater than 3: 4
Greater than 3: 5


In [43]:
indices = np.where(vector > 3)[0]
print("Indices of elements > 3:", indices)

Indices of elements > 3: [1 3 4]


In [45]:
total = 0
for element in vector:
    total += element

In [46]:
print("Sum of elements in vector:", total)

Sum of elements in vector: 23


In [47]:
row_sums = []
for row in matrix:
    row_sums.append(sum(row))
print("Row sums:", row_sums)

Row sums: [np.int64(6), np.int64(15)]


In [48]:
transposed = matrix.T
print("Transposed Matrix:\n", transposed)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [49]:
min_val = vector[0]
max_val = vector[0]
for element in vector:
    if element < min_val:
        min_val = element
    if element > max_val:
        max_val = element
print("Min:", min_val, "Max:", max_val)

Min: 1 Max: 10
